### ISSUE TITLE
Feature Request: Stop service when connected to specific wifi network

### ISSUE THREAD

**Issue by mikesellt** [Ch4t4r/Nebulo#14]
I have been running Nebulo for a couple days now, and it's great so far.  I run my own DNS server at my house for content filtering, etc... and with Nebulo I can connect to my private DNS from outside of my home LAN.  The problem is that when I get home I have to remember to stop Nebulo or else (I'm assuming because of VPN) I can't access LAN resources (like my file servers, Home Assistant, etc...).

Would it be possible to automatically stop the service when I'm connected to my home wifi, and then restart again once I am back on mobile data?  This isn't a big issue for me, but I'd also like my kids to do it, and I'd like the solution to be as hands off as possible.  Especially since I'll have Nebulo secured with a PIN so they can't connect or disconnect on their own.

**Comment by Ch4t4r** [comment]
On Android an app needs GPS access for it to see the names of WIFIs nearby (or the one you are connected to) + GPS has to be turned on at all times. Those are pretty big restrictions and sadly make such a feature not viable.

Nebulo intgerates into Tasker however, maybe that is automatable with that.

**Comment by mikesellt** [comment]
Thanks for the quick response!  That makes sense.  I'm checking out Tasker now.  I have a rule set up to stop Nebulo when I am connected to my wifi SSID, but it doesn't work...  I'm sure it's probably my Tasker config.  I'll keep checking on it.  Thanks again.  I'll go ahead and close this.
