### ISSUE TITLE
[Enhancement] Add option to disable auto connections

### ISSUE THREAD

**Issue by feeRnt** [Ch4t4r/Nebulo#7]
At present, it seems that when you launch the app, you connect to many different servers according to SECUSO Net Monitor.

Also, a particularly strange case that I've noticed is the app connecting to a Google IP address range after connecting to cloudflare-dns.com 

In general, these auto connections seem like a privacy concern to me when one has not inspected the source code.

I think it'd be great if there was an option to make it so that the connections are only made to the selected servers after turning on the VPN and to all the other servers only during the speed test. 

Version: 2.0.5-adblock

**Comment by Ch4t4r** [comment]
The connections you see are more than likely Nebulo trying to establish what would be a 'good' latency for your current network. It uses the latencies from popular servers (as they have the best networks) as comparisions for the server you currently use (the green,  yellow and red indicator next to the server)
https://github.com/Ch4t4r/Nebulo/blob/master/app/src/main/java/com/frostnerd/smokescreen/fragment/MainFragment.kt#L374

You are right that there is not yet an option to disable this. I'll add that.

**Comment by feeRnt** [comment]
Ah I see. That's pretty neat.

Thank you for clarifying and working on adding the option.

**Comment by Ch4t4r** [comment]
There is now a setting in the network tab
